name: Deploy DigitalPro

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run unit tests
        run: npm test
      
      - name: Run E2E tests
        run: echo "E2E tests would run here"

  build-docker:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build Docker image
        run: |
          docker build -t digitalpro:latest .
      
      - name: Save Docker image as artifact
        run: |
          docker save digitalpro:latest -o digitalpro-image.tar
      
      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v3
        with:
          name: digitalpro-docker-image
          path: digitalpro-image.tar

  deploy:
    runs-on: ubuntu-latest
    needs: build-docker
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    
    steps:
      - name: Download Docker image artifact
        uses: actions/download-artifact@v3
        with:
          name: digitalpro-docker-image
      
      - name: Load Docker image
        run: docker load -i digitalpro-image.tar
      
      - name: Deploy message
        run: |
          echo "✅ Приложение успешно собрано!"
          echo "📦 Docker-образ: digitalpro:latest"
          echo "🚀 Для деплоя выполните: docker run -p 8080:80 digitalpro:latest"
          echo "🌐 Или задеплойте на Vercel/Netlify"